service: helloworld-api

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  timeout: 10 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentPrefix: kumologica # The S3 prefix under which deployed artifacts should be stored.

functions:
  helloworld-flow:
    events:
      - http:
          path: hello
          method: get

plugins:
  - kumologica-serverless-plugin
